name: "Debugging"

on:
  pull_request: {}

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-24.04

    steps:
    - name: "Checkout"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Generate GitHub App Token"
      id: github-app-token
      uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: "Get GitHub App User ID"
      id: get-user-id
      env:
        APP_SLUG: ${{ steps.github-app-token.outputs.app-slug }}
        GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
      run: echo "user-id=$(gh api "/users/${{ env.APP_SLUG }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

    - name: "Set Commiter"
      env:
        APP_SLUG: ${{ steps.github-app-token.outputs.app-slug }}
        USER_ID: ${{ steps.get-user-id.outputs.user-id }}
      run: |
        git config --global user.name '${{ env.APP_SLUG }}[bot]'
        git config --global user.email '${{ env.USER_ID }}+${{ env.APP_SLUG }}[bot]@users.noreply.github.com'

    - name: "Calculate the Next Version"
      id: next-version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      with:
        github_token: ${{ steps.github-app-token.outputs.token }}
        dry_run: true

    - name: "Debug"
      env:
        NEW_VERSION: ${{ steps.next-version.outputs.new_version }}
      run: .github/scripts/debug.bash
