name: "Release / Bump / Tag / Draft"

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  bump-version:
    runs-on: ubuntu-24.04

    steps:
    - name: "Checkout"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: "Generate GitHub App Token"
      id: github-app-token
      uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: "Calculate the Next Version"
      id: next-version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      with:
        github_token: ${{ steps.github-app-token.outputs.token }}
        dry_run: true

    - name: "Configure Git Commiter"
      run: |
        git config --local user.email "1196749+afek-bot[bot]@users.noreply.github.com"
        git config --local user.name "afek-bot[bot]"

    - name: "Install Cargo V" # tool to update versions in Cargo.toml and Cargo.lock
      run: cargo install cargo-v

    - name: "Bump Version"
      run: cargo v --yes "${{ steps.next-version.outputs.new_version }}"

    - name: "Add back trailing empty line to Cargo.toml" # It seems cargo v is removing it
      run: |
        [ -n "$(tail -c1 Cargo.toml)" ] && echo >> Cargo.toml
        
        if ! git diff --quiet || ! git diff --cached --quiet; then
          git commit --all --signoff --amend --no-edit
          git tag --delete "${{ steps.next-version.outputs.new_tag }}"
          git tag "${{ steps.next-version.outputs.new_tag }}"
        fi

    - name: "Push Commit and Tag with New Version"
      uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master
      with:
        github_token: ${{ steps.github-app-token.outputs.token }}
        tags: true

    - name: "Draft a GitHub Release"
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        token: ${{ steps.github-app-token.outputs.token }}
        tag_name: ${{ steps.next-version.outputs.new_tag }}
        draft: true
        generate_release_notes: true
